### ISSUE TITLE
Whitelist IP

### ISSUE THREAD

**Issue by markruys** [jeromba6/transip_ddns#1]
This script updates TransIP DNS settings with your (new) public IP address. Like a DynDNS service. But the script only works for IP whitelisted key pairs. So as soon as your public IP address changes, the TransIP key pair is invalid. As I see it you need to set `global_key` to true in the auth call. What am I missing here?

**Comment by jeromba6** [comment]
> This script updates TransIP DNS settings with your (new) public IP address. Like a DynDNS service. But the script only works for IP whitelisted key pairs. So as soon as your public IP address changes, the TransIP key pair is invalid. As I see it you need to set `global_key` to true in the auth call. What am I missing here?

You know which provider you are running at so you can also look up what the Range is in which it operates. This way you have to allow only a range of IP's and don't have to use a global_key. You can find the range for your provider on https://www.ripe.net/ for at least european providers.
